import Navbar from './components/Navbar'
import Footer from './components/footer';
import "./globals.css";


export const metadata = {
  title: 'PANAVERSE-CO',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-white/10'>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
